I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00gamemenu.rpy", line 174, in script
    $ ui.interact()
  File "renpy/common/00gamemenu.rpy", line 174, in <module>
    $ ui.interact()
  File "game/replays/quick_start.rpy", line 21, in execute
    screen quick_start():
  File "game/replays/quick_start.rpy", line 21, in execute
    screen quick_start():
  File "game/replays/quick_start.rpy", line 39, in execute
    grid 6 3:
  File "game/replays/quick_start.rpy", line 43, in execute
    for replay in replays[current_chapter]:
  File "game/replays/quick_start.rpy", line 43, in <module>
    for replay in replays[current_chapter]:
KeyError: 'Chapter 1'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00gamemenu.rpy", line 174, in script
    $ ui.interact()
  File "Z:\home\troy\renpy-8.3.4-sdk\renpy\ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "Z:\home\troy\renpy-8.3.4-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00gamemenu.rpy", line 174, in <module>
    $ ui.interact()
  File "Z:\home\troy\renpy-8.3.4-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "Z:\home\troy\renpy-8.3.4-sdk\renpy\display\core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "Z:\home\troy\renpy-8.3.4-sdk\renpy\display\core.py", line 2745, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "Z:\home\troy\renpy-8.3.4-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "Z:\home\troy\renpy-8.3.4-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "Z:\home\troy\renpy-8.3.4-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  [Previous line repeated 1 more time]
  File "Z:\home\troy\renpy-8.3.4-sdk\renpy\display\screen.py", line 480, in visit_all
    callback(self)
  File "Z:\home\troy\renpy-8.3.4-sdk\renpy\display\core.py", line 2745, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "Z:\home\troy\renpy-8.3.4-sdk\renpy\display\screen.py", line 491, in per_interact
    self.update()
  File "Z:\home\troy\renpy-8.3.4-sdk\renpy\display\screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "game/replays/quick_start.rpy", line 21, in execute
    screen quick_start():
  File "game/replays/quick_start.rpy", line 21, in execute
    screen quick_start():
  File "game/replays/quick_start.rpy", line 39, in execute
    grid 6 3:
  File "game/replays/quick_start.rpy", line 43, in execute
    for replay in replays[current_chapter]:
  File "game/replays/quick_start.rpy", line 43, in <module>
    for replay in replays[current_chapter]:
KeyError: 'Chapter 1'

Windows-10-10.0.19043 AMD64
Ren'Py 8.3.4.24120703
Threat Hunters Splunk Edition 1.0
Sun Feb  9 22:57:23 2025
